server:
  port: 8080
spring:
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 100MB

  rabbitmq:
    username: 
    password: 
    host: 
    publisher-confirm-type: correlated
    publisher-returns: true

  application:
    name: weshare-server
  thymeleaf:
    cache: true
    check-template: true
    check-template-location: true
    content-type: text/html
    enabled: true
    encoding: UTF-8
    excluded-view-names: ''
    mode: HTML5
    prefix: classpath:/templates/
    suffix: .html

  datasource:
    username: 
    password: 
    #?serverTimezone=UTC解决时区的报错
    url: jdbc:mysql://47.113.194.136:3306/weshare?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

    druid:
      #Spring Boot 默认是不注入这些属性值的，需要自己绑定
      #druid 数据源专有配置
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true

      #配置监控统计拦截的filters，stat:监控统计、log4j：日志记录、wall：防御sql注入
      #如果允许时报错  java.lang.ClassNotFoundException: org.apache.log4j.Priority
      #则导入 log4j 依赖即可，Maven 地址：https://mvnrepository.com/artifact/log4j/log4j
      filters: stat,wall,log4j2
      maxPoolPreparedStatementPerConnectionSize: 20
      useGlobalDataSourceStat: true
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500

  redis:
    host: 
    database: 0
    port: 6379
    password: 
  cache:
    cache-names: weshare


mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml
  type-aliases-package: model
  configuration:
    map-underscore-to-camel-case: true           #配置mybatis全局的驼峰命名规则
    lazy-loading-enabled: true        #懒加载
    call-setters-on-nulls: true #空值映射

pagehelper:
  helperDialect:  mysql
  reasonable: true
  supportMethodsArguments:  true
  params: count=countSql

fdfs:
  # 连接超时时间
  connect-timeout: 1000
  # 读取时间
  so-timeout: 5000
  # tracker服务配置地址列表
  tracker-list: 



